const $=id=>document.getElementById(id);
const checks=[
{id:'notice',cat:'Notice',title:'Clear, standalone notice',severity:'High',patterns:[/privacy notice/i,/privacy policy/i,/clear and plain/i,/notice/i],legal:'Rule 3; DPDP Act s.5',explain:'The notice should be understandable on its own and explain the processing clearly.',fix:'Use a standalone notice in simple language.'},
{id:'data',cat:'Notice',title:'Itemised personal-data categories',severity:'High',patterns:[/name/i,/email/i,/phone|mobile/i,/address/i,/location/i,/device/i,/ip address/i],legal:'Rule 3(1)(b)(i)',explain:'The notice should identify the personal data being collected rather than relying only on vague wording.',fix:'List data categories for each relevant purpose.'},
{id:'purpose',cat:'Notice',title:'Specific purpose and enabled use',severity:'High',patterns:[/purpose/i,/service/i,/use your information/i],legal:'Rule 3(1)(b)(ii); DPDP Act s.5',explain:'People should understand why data is processed and what service or use it enables.',fix:'Map data categories to specific purposes and uses.'},
{id:'withdraw',cat:'Rights',title:'Easy consent withdrawal',severity:'High',patterns:[/withdraw.*consent/i,/unsubscribe/i,/opt[- ]out/i],legal:'Rule 3(1)(c)(i); DPDP Act s.6(9)',explain:'Where consent is the basis, withdrawal should be as easy as giving consent.',fix:'Provide a clear withdrawal route comparable to the consent journey.'},
{id:'rights',cat:'Rights',title:'Data Principal rights mechanism',severity:'High',patterns:[/exercise.*rights/i,/access.*personal data/i,/correction/i,/erasure/i,/delete.*data/i,/data principal/i],legal:'DPDP Act ss.11–14; Rule 14',explain:'The policy should explain how applicable rights can actually be exercised.',fix:'Publish request channels, identifiers and the rights workflow.'},
{id:'grievance',cat:'Rights',title:'Grievance redressal channel',severity:'High',patterns:[/grievance/i,/complaint/i,/grievance officer/i,/privacy.*contact/i],legal:'DPDP Act s.13; Rule 14',explain:'A practical complaint channel and response period should be published.',fix:'Provide a contact, escalation route and stated response period.'},
{id:'security',cat:'Security',title:'Reasonable security safeguards',severity:'High',patterns:[/encrypt/i,/mask/i,/obfuscat/i,/access control/i,/authentication/i,/backup/i,/security safeguards/i],legal:'Rule 6; DPDP Act s.8(5)',explain:'Policy evidence should mention meaningful safeguards; policy wording alone is not proof that controls operate.',fix:'Describe relevant technical and organisational safeguards.'},
{id:'breach',cat:'Security',title:'Personal-data breach response',severity:'High',patterns:[/data breach/i,/security breach/i,/72 hours/i,/seventy[- ]two hours/i,/without delay/i],legal:'Rule 7; DPDP Act s.8(6)',explain:'Rule 7 requires notice to affected Data Principals without delay and detailed information to the Board within 72 hours unless a longer period is allowed.',fix:'Document and test the breach notification process.'},
{id:'children',cat:'Children',title:'Child-data / verifiable parental consent',severity:'High',patterns:[/child/i,/under 18/i,/parental consent/i,/verifiable consent/i],legal:'DPDP Act s.9; Rules 10–12',explain:'If children are in scope, the policy should address age handling and verifiable parental consent, subject to statutory exemptions.',fix:'Document child-data scope, verification and any applicable exemption.'},
{id:'retention',cat:'Retention',title:'Retention and deletion rules',severity:'High',patterns:[/retain/i,/retention/i,/delete/i,/deletion/i,/erase/i,/erasure/i],legal:'DPDP Act s.8(7)–(8); Rule 8 and Third Schedule',explain:'Retention should relate to purpose and legal requirements. Certain large e-commerce, social-media and online-gaming entities have additional three-year erasure requirements with exceptions.',fix:'Publish periods or criteria, deletion triggers and legal-retention exceptions.'},
{id:'logs',cat:'Retention',title:'Required one-year operational retention',severity:'Medium',patterns:[/one year/i,/12 months/i,/processing logs/i,/logs/i],legal:'Rule 6(1)(e) and Rule 8(3), where applicable',explain:'The one-year requirement applies to specified security logs/data and specified Rule 8 purposes; it is not a universal one-year rule for every dataset.',fix:'Maintain and document required operational log retention.'},
{id:'processors',cat:'Third parties',title:'Processor / third-party transparency',severity:'Medium',patterns:[/data processor/i,/service provider/i,/third part/i,/vendor/i,/share.*data/i],legal:'DPDP Act s.8; Rule 6(1)(f)',explain:'Processor relationships require appropriate safeguards and contractual controls.',fix:'Explain processor categories, purposes and relevant safeguards.'},
{id:'crossborder',cat:'Transfers',title:'Cross-border transfer disclosure',severity:'Medium',patterns:[/cross[- ]border/i,/international transfer/i,/outside india/i,/overseas/i],legal:'DPDP Act s.16; Rule 13(4) for specified SDF data',explain:'International transfers/access should be disclosed where relevant. Restrictions can apply through Central Government notifications and SDF obligations.',fix:'State whether international access/transfers occur and explain applicable safeguards.'},
{id:'sdf',cat:'SDF',title:'Significant Data Fiduciary readiness',severity:'Critical',patterns:[/significant data fiduciary/i,/data protection impact assessment/i,/DPIA/i,/independent data auditor/i,/annual audit/i],legal:'DPDP Act s.10; Rule 13',explain:'Enhanced SDF duties apply when the entity is notified or included in a notified class. They include annual DPIA and audit and other Rule 13 duties.',fix:'Verify SDF status, then assess DPO, auditor, annual DPIA/audit and Rule 13 controls.'},
{id:'contact',cat:'Accountability',title:'Privacy contact / responsible person',severity:'Medium',patterns:[/privacy officer/i,/data protection officer/i,/DPO/i,/privacy team/i,/contact us/i],legal:'DPDP Act ss.10,13 where applicable',explain:'A practical privacy contact supports rights and grievance handling; SDFs have a specific India-based DPO requirement.',fix:'Publish an appropriate privacy contact and verify SDF DPO requirements where applicable.'}
];
const lang={en:{title:'DPDP Privacy Policy Checker',subtitle:'A browser-only, evidence-based screening tool for Indian privacy-policy readiness.',input:'Company or Privacy Policy URL',help:'An exact Privacy Policy URL is preferred. A homepage can be supplied, but automatic discovery is limited because browsers enforce CORS.',review:'Read policy',paste:'Paste Privacy Policy text',run:'Run gap assessment',pdf:'Save / Export PDF'},hi:{title:'DPDP गोपनीयता नीति जाँच',subtitle:'भारत में गोपनीयता नीति की तैयारी के लिए ब्राउज़र-आधारित जाँच उपकरण।',input:'कंपनी या Privacy Policy URL',help:'सटीक Privacy Policy URL बेहतर है। होमपेज से शुरुआत की जा सकती है, लेकिन ब्राउज़र CORS नियमों के कारण स्वतः खोज सीमित है।',review:'नीति पढ़ें',paste:'Privacy Policy का पाठ चिपकाएँ',run:'गैप असेसमेंट चलाएँ',pdf:'PDF सेव / एक्सपोर्ट करें'},mr:{title:'DPDP गोपनीयता धोरण तपासणी',subtitle:'भारतीय गोपनीयता धोरणाच्या तयारीसाठी ब्राउझर-आधारित तपासणी साधन.',input:'कंपनी किंवा Privacy Policy URL',help:'अचूक Privacy Policy URL अधिक चांगला आहे. होमपेज वापरता येतो, पण ब्राउझरच्या CORS नियमांमुळे स्वयंचलित शोध मर्यादित आहे.',review:'धोरण वाचा',paste:'Privacy Policy चा मजकूर पेस्ट करा',run:'गॅप असेसमेंट चालवा',pdf:'PDF सेव्ह / एक्सपोर्ट करा'}};
function clean(s){return s.replace(/\s+/g,' ').trim()}
function risk(n,t){const r=t?n/t:0;return r<.35?'Critical':r<.55?'High':r<.75?'Medium':'Low'}
function setLanguage(v){const x=lang[v]||lang.en;document.documentElement.lang=v; $('title').textContent=x.title;$('subtitle').textContent=x.subtitle;$('inputTitle').textContent=x.input;$('urlHelp').textContent=x.help;$('scan').textContent=x.review;$('assess').textContent=x.run}
async function readUrl(){const raw=$('url').value.trim();if(!raw)return;let u;try{u=new URL(raw);if(!/^https?:$/.test(u.protocol))throw new Error('Only http/https URLs are supported.')}catch(e){$('urlStatus').textContent=e.message;return}$('urlStatus').textContent='Trying to read this page locally. No policy text is sent to this site.';try{const c=new AbortController();const timer=setTimeout(()=>c.abort(),9000);const r=await fetch(u.href,{redirect:'follow',signal:c.signal,headers:{Accept:'text/html,text/plain'}});clearTimeout(timer);if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const txt=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ');if(clean(txt).length<300)throw new Error('The page did not contain enough readable text.');$('policy').value=clean(txt);$('urlStatus').textContent='Policy text read locally. Confirm that this is the intended Privacy Policy page.';assess()}catch(e){$('urlStatus').textContent=`Automatic reading failed or was blocked (${e.name==='AbortError'?'timed out':e.message}). Paste the exact policy text below and run the assessment.`}}
function assess(){const text=clean($('policy').value);if(text.length<100){$('urlStatus').textContent='Please provide at least 100 characters of policy text.';return}const rs=checks.map(c=>({...c,found:c.patterns.some(p=>p.test(text))}));const found=rs.filter(x=>x.found).length;const r=risk(found,rs.length);$('report').classList.remove('hidden');$('source').textContent=$('url').value.trim()||'Supplied policy text';$('risk').textContent=r;$('risk').style.color=r==='Critical'?'var(--red)':r==='High'?'var(--red)':r==='Medium'?'var(--amber)':'var(--green)';$('score').textContent=`${found}/${rs.length}`;$('count').textContent=String(rs.length);$('results').innerHTML=rs.map(x=>`<article class="result ${x.found?'pass':'gap'}"><div class="topline"><div><span class="eyebrow">${escapeHtml(x.cat)}</span><h3>${escapeHtml(x.title)}</h3></div><span class="tag">${x.found?'✓ Evidence found':`Gap • ${x.severity}`}</span></div><p>${escapeHtml(x.explain)}</p><p class="legal"><strong>Legal reference:</strong> ${escapeHtml(x.legal)}</p>${x.found?'':`<p><strong>Recommended action:</strong> ${escapeHtml(x.fix)}</p>`}</article>`).join('');$('report').scrollIntoView({behavior:'smooth',block:'start'})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('scan').addEventListener('click',readUrl);$('assess').addEventListener('click',assess);$('clear').addEventListener('click',()=>{$('url').value='';$('policy').value='';$('urlStatus').textContent='';$('report').classList.add('hidden')});$('print').addEventListener('click',()=>window.print());$('language').addEventListener('change',e=>setLanguage(e.target.value));
