/*
 * DPDP evidence matrix
 *
 * This is a screening knowledge base, not a legal opinion. Each control says
 * what can be evidenced from a public privacy notice and what cannot.
 * "Not determinable" is intentionally a first-class outcome.
 */
window.DPDP_MATRIX = [
  {id:'notice-itemised',area:'Notice & transparency',priority:'High',act:'DPDP Act s.5',rules:'Rule 3(1)(b)(i)',status:'18-month commencement bucket',title:'Itemised personal-data categories',citizen:'The notice should tell you what kinds of personal data are being collected, not just say “your information”.',evidence:['name','email','phone','mobile','address','location','device','identifier','financial','biometric','personal data'],manual:'Check whether categories are complete and actually tied to the stated purposes.',remediation:'List personal-data categories in clear, standalone notice language.'},
  {id:'notice-purpose',area:'Notice & transparency',priority:'High',act:'DPDP Act s.5',rules:'Rule 3(1)(b)(ii)',status:'18-month commencement bucket',title:'Purpose and service/use explanation',citizen:'You should be able to understand why the organisation needs your data and what service or use it enables.',evidence:['purpose','provide our services','service','use your information','process your data','legal obligation'],manual:'Check whether each important data category has a specific purpose rather than a broad catch-all.',remediation:'Map each data category to a clear purpose and service/use.'},
  {id:'consent-withdrawal',area:'Consent & choice',priority:'High',act:'DPDP Act s.6(9)',rules:'Rule 3(1)(c)(i)',status:'18-month commencement bucket',title:'Withdrawal of consent',citizen:'If consent is the basis for processing, withdrawing it should be as easy as giving it.',evidence:['withdraw consent','withdrawal of consent','unsubscribe','opt out','manage preferences'],manual:'Test the actual journey; a sentence in the policy is not proof that withdrawal is equally easy.',remediation:'Provide a clear withdrawal route and make it comparable to the consent journey.'},
  {id:'rights',area:'Data Principal rights',priority:'High',act:'DPDP Act ss.11–14',rules:'Rule 14',status:'18-month commencement bucket',title:'Rights and exercise mechanism',citizen:'The site should explain how you can request access, correction/update, erasure and other applicable rights.',evidence:['access your data','access personal data','correct','correction','update','erase','erasure','delete your data','exercise your rights','data principal'],manual:'Verify request channels, authentication/verification, response process and exceptions.',remediation:'Publish a practical rights-request process, contact route and escalation information.'},
  {id:'grievance',area:'Grievance',priority:'High',act:'DPDP Act s.13',rules:'Rule 14',status:'18-month commencement bucket',title:'Grievance redressal',citizen:'If something goes wrong, you should know where to complain and how the complaint is handled.',evidence:['grievance','complaint','grievance officer','privacy contact','contact us'],manual:'Confirm the channel works and assess the stated response period against the applicable law.',remediation:'Publish a dedicated grievance mechanism and escalation route.'},
  {id:'security',area:'Security',priority:'High',act:'DPDP Act s.8(5)',rules:'Rule 6',status:'18-month commencement bucket',title:'Reasonable security safeguards',citizen:'The organisation should describe meaningful safeguards used to protect personal data.',evidence:['encrypt','encryption','mask','obfuscat','access control','authentication','backup','security safeguards','log'],manual:'A policy statement cannot prove technical effectiveness. Validate controls, configurations, contracts and testing separately.',remediation:'Document appropriate technical and organisational safeguards and verify their implementation.'},
  {id:'breach',area:'Security & breach',priority:'Critical',act:'DPDP Act s.8(6)',rules:'Rule 7',status:'18-month commencement bucket',title:'Personal-data breach notification',citizen:'If a breach affects you, the framework requires notification without delay. The Board receives detailed information within 72 hours unless a longer period is allowed.',evidence:['data breach','personal data breach','security incident','without delay','72 hours','seventy-two hours'],manual:'Test incident classification, affected-person communication, Board notification and evidence of the incident process.',remediation:'Maintain and test an incident-response and notification process aligned to Rule 7.'},
  {id:'children',area:'Children',priority:'Critical',act:'DPDP Act s.9',rules:'Rules 10–12',status:'18-month commencement bucket',title:'Children and verifiable parental consent',citizen:'If children may use the service, special rules apply to processing children’s data and consent.',evidence:['child','children','under 18','parental consent','verifiable consent','parent'],manual:'Determine age handling, consent verification, child safety controls and whether a statutory exemption applies.',remediation:'Document child-data scope, age assurance, verifiable parental consent and applicable exemptions.'},
  {id:'retention',area:'Retention & erasure',priority:'High',act:'DPDP Act s.8(7)–(8)',rules:'Rule 8 + Third Schedule',status:'18-month commencement bucket',title:'Retention and erasure',citizen:'The organisation should explain how long it keeps data or the criteria used to decide retention, and when data is erased.',evidence:['retention','retain','delete','deletion','erase','erasure','destroy'],manual:'Check purpose-based retention and statutory exceptions. For specified large e-commerce/social-media/online-gaming entities, verify the additional Third Schedule trigger.',remediation:'Publish retention periods or objective criteria, deletion triggers and legal-retention exceptions.'},
  {id:'logs',area:'Retention & security',priority:'Medium',act:'DPDP Act s.8(5)',rules:'Rule 6(1)(e); Rule 8(3), where applicable',status:'18-month commencement bucket',title:'Required one-year records/log retention',citizen:'The one-year rule is not a blanket instruction to keep all your personal data for one year. It applies to specified records/logs and purposes.',evidence:['one year','12 months','logs','processing logs','traffic data'],manual:'Determine whether the specific Rule 6/Rule 8 retention context applies to the organisation.',remediation:'Implement and document only the retention required by the applicable Rule.'},
  {id:'processors',area:'Third parties',priority:'Medium',act:'DPDP Act s.8',rules:'Rule 6(1)(f)',status:'18-month commencement bucket',title:'Processor and third-party disclosures',citizen:'The organisation may use vendors to process your data. The policy should explain relevant categories and purposes.',evidence:['data processor','processor','service provider','third party','vendor','share your data','disclose'],manual:'Review processor contracts, sub-processors, purposes and security obligations.',remediation:'Maintain processor due diligence and contractual safeguards and provide appropriate transparency.'},
  {id:'transfers',area:'Transfers',priority:'Medium',act:'DPDP Act s.16',rules:'Rule 13(4) for specified SDF data',status:'Depends on commencement/applicability',title:'Cross-border processing and transfers',citizen:'Your data may be accessed or processed outside India. The organisation should be transparent about this where relevant.',evidence:['cross-border','international transfer','outside India','overseas','global data','international data'],manual:'Check current Central Government restrictions and, if SDF, Rule 13(4) requirements.',remediation:'Document transfer destinations, purposes and applicable legal/security safeguards.'},
  {id:'sdf',area:'Significant Data Fiduciary',priority:'Critical',act:'DPDP Act s.10',rules:'Rule 13',status:'Only if notified/classified as SDF',title:'SDF enhanced obligations',citizen:'Some organisations may be notified as Significant Data Fiduciaries and have additional safeguards and accountability duties.',evidence:['significant data fiduciary','SDF','data protection impact assessment','DPIA','independent data auditor','annual audit','algorithmic'],manual:'First establish whether the entity is actually notified as an SDF. Then assess DPO, annual DPIA/audit, algorithmic due diligence and other Rule 13 duties.',remediation:'Verify SDF status and implement the applicable Rule 13 governance programme.'},
  {id:'contact',area:'Accountability',priority:'Medium',act:'DPDP Act ss.10,13 where applicable',rules:'Rule 14',status:'Applicability-dependent',title:'Privacy/DPO/grievance contact',citizen:'A clear contact makes it easier to exercise rights or complain.',evidence:['data protection officer','DPO','privacy officer','privacy team','grievance officer','contact us'],manual:'For an SDF, verify the India-based DPO and required publication/contact duties.',remediation:'Publish an appropriate privacy/grievance contact and verify SDF DPO obligations where applicable.'}
];
